### ISSUE TITLE
graphene_dataset can't be trained

### ISSUE THREAD

**Issue by qingmo-nscc-gz** [mzjb/DeepH-pack#3]
It can't be trained because graph.py will raise NotImplemented exception. This exception is caused when the configuration parameter "interface" is not in ['h5', 'h5_rc_only'] and the parameter "create_from_DFT" is True. But if I change this parameter "interface" to "h5", the dataset can't find any structure because the rc and rh file ends with "npz".

**Comment by mzjb** [comment]
Datasets for MoS$_2$, twisted bilayer graphene and twisted bilayer bismuthene are in the format of HDF5, and the parameter `interface` should be set to `h5`. While, dataset for graphene is in a older format of NPZ. The parameter `interface` should be set to `npz`. See also the referenced config file:
https://github.com/mzjb/DeepH-pack/blob/main/ini/graphene.ini
and the README:
https://github.com/mzjb/DeepH-pack#:~:text=files%20in%20the-,DeepH%2Dpack/ini/,-.%20raw_dir%20should

**Comment by qingmo-nscc-gz** [comment]
![image](https://user-images.githubusercontent.com/59354466/179184161-fa5b4dec-fee4-446c-892c-664f4a081918.png)
![image](https://user-images.githubusercontent.com/59354466/179184385-8fb3cc7a-92da-4d1b-9b14-2703980a702b.png)

**Comment by qingmo-nscc-gz** [comment]
The first screenshot is my ini file, the second is the exception

**Comment by qingmo-nscc-gz** [comment]
I used npz, but it still can't work

**Comment by mzjb** [comment]
There is something wrong with the referenced config file [graphene.ini](https://github.com/mzjb/DeepH-pack/blob/main/ini/graphene.ini) I provided. I didn't implement `create_from_DFT ` for the `npz` case. I have fixed this bug in this [commit](https://github.com/mzjb/DeepH-pack/commit/d7a67deb92ccb85c29a85901ebfc5b01255bf705). Thank you for your feedback.

**Comment by qingmo-nscc-gz** [comment]
![image](https://user-images.githubusercontent.com/59354466/179189859-091bc54f-5771-4186-b8da-a0224c976b29.png)
Then I caught another exception

**Comment by mzjb** [comment]
> ![image](https://user-images.githubusercontent.com/59354466/179184161-fa5b4dec-fee4-446c-892c-664f4a081918.png) ![image](https://user-images.githubusercontent.com/59354466/179184385-8fb3cc7a-92da-4d1b-9b14-2703980a702b.png)

Could you replace the screenshot with pasted text so that others can search for this issue with the error message?

**Comment by qingmo-nscc-gz** [comment]
I have replaced all screenshot now. But it still can't work. When I changed create_from_DFT to False, I got another exception. 
```
File "/data/xxx/anaconda2/envs/deeph/lib/python3.9/site-packages/deeph/graph.py", line 517, in get_graph
    nn_coords_index = np.concatenate([cube_to_coords_index[k] for k in ks], axis=0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by mzjb** [comment]
> I have replaced all screenshot now. But it still can't work. When I changed create_from_DFT to False, I got another exception.
> 
> ```
> File "/data/xxx/anaconda2/envs/deeph/lib/python3.9/site-packages/deeph/graph.py", line 517, in get_graph
>     nn_coords_index = np.concatenate([cube_to_coords_index[k] for k in ks], axis=0)
>   File "<__array_function__ internals>", line 180, in concatenate
> ValueError: need at least one array to concatenate
> ```

The dataset for graphene in the format of `npz` was generated a year ago, the `npz` interface has not been maintained recently, sorry for some bugs. I just found another bug for the `npz` interface and fixed it in the [commit](https://github.com/mzjb/DeepH-pack/commit/884a430092b05a1a30bac1cea2a24fbeb508d09f). However, I can't reproduce your exception. Now I can successfully generate graph data for graphene dataset:
```
Graph data file: HGraph-npz-graphene-5l-6.0r0mn.pkl
Process new data file......
Found 450 structures, have cost 0 seconds
 15%|#5        | 69/450 [03:30<19:30,  3.07s/it]
```
